Library/Controllers/BranchController.cs
using Library.Models.Branch;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class BranchController : Controller
    {
        #region Properties

        private readonly ILibraryBranchService libraryBranchService;

        #endregion

        #region Constructor
        public BranchController(ILibraryBranchService branchService)
        {
            libraryBranchService = branchService;
        }

        #endregion

        #region Methods

        public IActionResult Index()
        {
            var branches = libraryBranchService.GetAll();

            var branchDetailModels = branches.Select(b => new BranchDetailModel
            {
                Address = b.Address,
                BusinessHours = libraryBranchService.GetBranchHours(b.Id),
                Description = b.Description,
                Id = b.Id,
                ImageUrl = b.ImageUrl,
                IsOpen = libraryBranchService.IsBranchOpen(b.Id),
                Name = b.Name,
                NumberOfAssets = libraryBranchService.GetAssets(b.Id).Count(),
                NumberOfPatrons = libraryBranchService.GetPatrons(b.Id).Count(),
                OpenDate = b.OpenDate.ToString("yyyy-MM-dd"),
                Telephone = b.TelephoneNumber,
                TotalAssetValue = libraryBranchService.GetAssets(b.Id).Sum(a => a.Cost)
            });

            var model = new BranchIndexModel
            {
                Branches = branchDetailModels
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var branch = libraryBranchService.GetById(id);

            var model = new BranchDetailModel
            {
                Address = branch.Address,
                BusinessHours = libraryBranchService.GetBranchHours(branch.Id),
                Description = branch.Description,
                Id = branch.Id,
                ImageUrl = branch.ImageUrl,
                IsOpen = libraryBranchService.IsBranchOpen(branch.Id),
                Name = branch.Name,
                NumberOfAssets = libraryBranchService.GetAssets(branch.Id).Count(),
                NumberOfPatrons = libraryBranchService.GetPatrons(branch.Id).Count(),
                OpenDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                Telephone = branch.TelephoneNumber,
                TotalAssetValue = libraryBranchService.GetAssets(branch.Id).Sum(a => a.Cost)
            };

            return View(model);
        }

        #endregion
    }
}

Library/Controllers/CatalogController.cs
using Library.Models.Catalog;
using Library.Models.Catalog.CheckOut;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Library.Controllers
{
    public class CatalogController : Controller
    {
        #region Properties

        private readonly ILibraryAssetService libraryAsset;
        private readonly ILibraryCheckoutService checkoutService;

        #endregion Properties

        #region Constructor

        public CatalogController(ILibraryAssetService libAsset, ILibraryCheckoutService checkout)
        {
            libraryAsset = libAsset;
            checkoutService = checkout;
        }

        #endregion Constructor

        #region Methods

        public IActionResult Index()
        {
            var assetModels = libraryAsset.GetAll();

            var listingResult =
                    assetModels.Select(result => new AssetIndexListingModel
                    {
                        AuthorOrDirector = libraryAsset.GetAuthorOrDirector(result.Id),
                        DeweyCallNumber = libraryAsset.GetDeweyIndex(result.Id),
                        Id = result.Id,
                        ImageUrl = result.ImageUrl,
                        NumberOfCopies = result.NumberOfCopies,
                        Title = result.Title,
                        Type = libraryAsset.GetType(result.Id)
                    });

            var model = new AssetIndexModel { Assets = listingResult };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var asset = libraryAsset.GetById(id);

            var currentHolds = checkoutService.GetCurrentHolds(id)
                                .Select(a => new AssetHoldModel
                                {
                                    //HoldPlaced = checkoutService.GetCurrentHoldPlaced(a.Id).ToString("d"),
                                    PatronName = checkoutService.GetCurrentHoldPatronName(a.Id)
                                });

            var model = new AssetDetailModel
            {
                AssetId = id,
                AuthorOrDirector = libraryAsset.GetAuthorOrDirector(id),
                Cost = asset.Cost,
                CurrentLocation = asset.Location.Name,
                DeweyCallNumber = libraryAsset.GetDeweyIndex(id),
                ImageUrl = asset.ImageUrl,
                ISBN = libraryAsset.GetIsbn(id),
                Status = asset.Status.Name,
                Title = asset.Title,
                Type = libraryAsset.GetType(id),
                Year = asset.Year,
                CheckoutHistory = checkoutService.GetCheckoutHistory(id),
                LatestCheckout = checkoutService.GetLatestCheckout(id),
                PatronName = checkoutService.GetCurrentCheckoutPatron(id),
                CurrentHolds = currentHolds  
            };

            return View(model);
        }

        public IActionResult Checkout(int id)
        {
            var asset = libraryAsset.GetById(id);

            var checkoutModel = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                IsCheckedOut = checkoutService.IsCheckedout(id),
                LibraryCardId = "",
            };

            return View(checkoutModel);
        }

        public IActionResult CheckIn(int id)
        {
            checkoutService.CheckInItem(id);
            return RedirectToAction("Detail", new { id });
        }
        public IActionResult Hold(int id)
        {
            var asset = libraryAsset.GetById(id);

            var checkoutModel = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                IsCheckedOut = checkoutService.IsCheckedout(id),
                LibraryCardId = "",
                HoldCount = checkoutService.GetCurrentHolds(id).Count()
            };

            return View(checkoutModel);
        }

        public IActionResult MarkLost(int id)
        {
            checkoutService.MarkLost(id);
            return RedirectToAction("Detail", new { id });
        }

        public IActionResult MarkFound(int id)
        {
            checkoutService.MarkFound(id);
            return RedirectToAction("Detail", new { id });
        }

        [HttpPost]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId)
        {
            checkoutService.CheckOutItem(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            checkoutService.PlaceHold(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        #endregion Methods
    }
}

Library/Controllers/PatronController.cs
using Library.Models.Patron;
using LibraryData;
using LibraryData.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Library.Controllers
{
    public class PatronController : Controller
    {
        #region Properties

        private ILibraryPatronService libraryPatronService;

        #endregion

        #region Constructor

        public PatronController(ILibraryPatronService patronService)
        {
            libraryPatronService = patronService;
        }

        #endregion

        #region Methods

        public IActionResult Index()
        {
            var allPatrons = libraryPatronService.GetAll();

            var patronDetailModels = allPatrons.Select(p => new PatronDetailModel
            {
                Address = p.Address,
                AssetsCheckedOut = libraryPatronService.GetCheckouts(p.Id),
                CheckoutHistory = libraryPatronService.GetCheckoutHistory(p.Id),
                FirstName = p.FirstName,
                Holds = libraryPatronService.GetHolds(p.Id),
                Id = p.Id,
                HomeLibraryBranch = p.HomeLibraryBranch.Name,
                LastName = p.LastName,
                LibraryCardId = p.LibraryCard.Id,
                MemberSince = p.LibraryCard.Created,
                OverdueFees = p.LibraryCard.Fees,
                Telephone = p.TelephoneNumber,
            }).ToList();

            var model = new PatronIndexModel
            {
                Patrons = patronDetailModels
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var patron = libraryPatronService.GetById(id);

            var model = new PatronDetailModel
            {
                Address = patron.Address,
                AssetsCheckedOut = libraryPatronService.GetCheckouts(id).ToList() ?? new List<Checkout>(),
                CheckoutHistory = libraryPatronService.GetCheckoutHistory(id).ToList() ?? new List<CheckoutHistory>(),
                FirstName = patron.FirstName,
                Holds = libraryPatronService.GetHolds(id).ToList() ?? new List<Hold>(),
                HomeLibraryBranch = patron.HomeLibraryBranch.Name,
                Id = patron.Id,
                LastName = patron.LastName,
                LibraryCardId = patron.LibraryCard.Id,
                MemberSince = patron.LibraryCard.Created,
                OverdueFees = patron.LibraryCard.Fees,
                Telephone = patron.TelephoneNumber
            };

            return View(model);
        }

        #endregion
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link href=”//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css” rel=”stylesheet”>
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title logo"><a href="/">FrancxSoft</a></span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                    <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                    <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">LightLib</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
            </nav>
        </div>
        <div class="page-content">
            @RenderBody()
        </div>
    </div>

    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
    <script src="https://use.fontawesome.com/6110b02b27.js"></script>
</body>
</html>